pub mod coloring_solvability;
pub mod diagram;
pub mod line_inclusion;
pub mod line_normalizer;
pub mod max_clique;
pub mod maximize;
pub mod part_parser;
pub mod problem_triviality;
pub mod useless_lines;